name: cat_trivia
description: Learn new facts about cats

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  retrofit: ^3.0.1+1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  hive_generator: ^1.1.3
  retrofit_generator: ^4.0.3+1

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
          weight: 400

        - asset: assets/fonts/Cabin-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Cabin-Medium.ttf
          weight: 500

        - asset: assets/fonts/Cabin-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Cabin-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Cabin-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Cabin-Bold.ttf
          weight: 700

        - asset: assets/fonts/Cabin-BoldItalic.ttf
          weight: 700
          style: italic
